### ISSUE TITLE
Multiple galleries interaction

### ISSUE THREAD

**Issue by OrenBochman** [jsilvermist/sl-gallery#1]
with multiple galleries on a page a click on a n-th thumbnail of the first gallery will open the respective image in the last gallery.

**Comment by jsilvermist** [comment]
The galleries will by default use a prefix of `i` , if you manually set a different prefix on each gallery using `prefix="something-unique"` do you still run in to any problems?

**Comment by jsilvermist** [comment]
@OrenBochman To add on to the previous answer, here's an example of that I mean taken from the demos page:

```html
<!--
  This gallery will default to using a prefix of `i` to namespace the url hash for this gallery.
  Eg. `mywebsite.com/gallery#/i/0` for the first picture in the gallery.
-->
<sl-gallery></sl-gallery>

<!--
  This gallery will use a prefix of `something-unique` to namespace the url hash for this gallery.
  Eg. `mywebsite.com/gallery#/something-unique/0` for the first picture in the gallery.
-->
<sl-gallery prefix="something-unique"></sl-gallery>
```

If this solves your problem, please close this issue.

**Comment by OrenBochman** [comment]
Thanks I got to to work fine!

**Comment by jsilvermist** [comment]
@OrenBochman Awesome! 👍
