### ISSUE TITLE
Grid displays incorrectly in Edge

### ISSUE THREAD

**Issue by zalcorn** [jsilvermist/sl-gallery#4]
In MS Edge (40.15063.674.0), the photo grid is broken, displaying one image per line at 100% width of container. Reproducible in the demo on webcomponents.org. Not reproducible on Chrome 63 or Firefox 57.

**Comment by jsilvermist** [comment]
Can't reproduce on `Microsoft Edge 41.16299.15.0`, is there any way you could update Edge and tell me if the problem persists?

**Comment by zalcorn** [comment]
Yep issue is gone in Microsoft Edge 41.16299.15.0. Thanks!
