### ISSUE TITLE
2.3.2 release ETA?

### ISSUE THREAD

**Issue by Pupix** [jsilvermist/sl-gallery#7]
Hello,

Is there any ETA regarding the 2.3.2 release? I'm trying to use your gallery with dom-repeat, which breaks in the 2.3.1 version and I see that you fixed it in 2.3.2 but it's not published yet.

Cheers,
Pupix

**Comment by jsilvermist** [comment]
Ah my apologies, I thought that I had already added a release for it! Fixed now.

**Comment by jsilvermist** [comment]
SORRY SORRY!!! For some reason it hadn't gone through again, but THIS TIME!!! I can confirm it published properly! (https://www.npmjs.com/package/@silverlinkz/sl-gallery/v/2.3.2)
